export type PhysicsAsset = {
  id: string;
  title: string;
  category: "real" | "symbol" | "diagram";
  topic: "electricity";
  src: string;
  alt: string;
  credit: string;
  license: string;
  standardNote?: string;
  sourceRefs: string[];
  usage: string[];
};

const base = "/Lernplattform_Physik_3/assets/electricity/";

export const electricityAssets: Record<string, PhysicsAsset> = {
  batteryReal: {
    id: "el-real-battery-01",
    title: "Spannungsquelle",
    category: "real",
    topic: "electricity",
    src: base + "real/battery.svg",
    alt: "Stilisierte Spannungsquelle mit Plus- und Minuspol",
    credit: "Eigene Illustration · Physik 3",
    license: "Projektintern erstellt",
    sourceRefs: ["P3-K3-S044-M02", "P3-K3-S045-M01"],
    usage: ["matching", "grouping", "diagram-labeling"],
  },
  lampReal: {
    id: "el-real-lamp-01",
    title: "Lampe",
    category: "real",
    topic: "electricity",
    src: base + "real/lamp.svg",
    alt: "Stilisierte Glühlampe als elektrisches Gerät",
    credit: "Eigene Illustration · Physik 3",
    license: "Projektintern erstellt",
    sourceRefs: ["P3-K3-S044-M02", "P3-K3-S045-M01"],
    usage: ["matching", "grouping", "diagram-labeling"],
  },
  switchOpenReal: {
    id: "el-real-switch-open-01",
    title: "Schalter offen",
    category: "real",
    topic: "electricity",
    src: base + "real/switch-open.svg",
    alt: "Stilisierter geöffneter Schalter",
    credit: "Eigene Illustration · Physik 3",
    license: "Projektintern erstellt",
    sourceRefs: ["P3-K3-S044-M02"],
    usage: ["matching", "grouping"],
  },
  switchClosedReal: {
    id: "el-real-switch-closed-01",
    title: "Schalter geschlossen",
    category: "real",
    topic: "electricity",
    src: base + "real/switch-closed.svg",
    alt: "Stilisierter geschlossener Schalter",
    credit: "Eigene Illustration · Physik 3",
    license: "Projektintern erstellt",
    sourceRefs: ["P3-K3-S044-M02"],
    usage: ["matching", "grouping"],
  },
  resistorReal: {
    id: "el-real-resistor-01",
    title: "Widerstand",
    category: "real",
    topic: "electricity",
    src: base + "real/resistor.svg",
    alt: "Stilisierter elektrischer Widerstand",
    credit: "Eigene Illustration · Physik 3",
    license: "Projektintern erstellt",
    sourceRefs: ["P3-K3-S048-M01", "P3-K3-S048-M02"],
    usage: ["matching", "grouping"],
  },
  ammeterReal: {
    id: "el-real-ammeter-01",
    title: "Amperemeter",
    category: "real",
    topic: "electricity",
    src: base + "real/ammeter.svg",
    alt: "Stilisiertes Amperemeter mit Skala und dem Zeichen A",
    credit: "Eigene Illustration · Physik 3",
    license: "Projektintern erstellt",
    sourceRefs: ["P3-K3-S047-M01", "P3-FD-018"],
    usage: ["matching", "grouping", "diagram-labeling"],
  },
  batterySymbol: {
    id: "el-symbol-battery-01",
    title: "Schaltsymbol Batterie",
    category: "symbol",
    topic: "electricity",
    src: base + "symbols/battery.svg",
    alt: "Schaltsymbol einer Batterie mit langen und kurzen parallelen Linien",
    credit: "Eigene Vektorgrafik · Physik 3",
    license: "Projektintern erstellt",
    standardNote: "IEC-orientierte europäische Unterrichtsdarstellung; eigenständig gezeichnet.",
    sourceRefs: ["P3-K3-S045-M02"],
    usage: ["matching", "diagram"],
  },
  lampSymbol: {
    id: "el-symbol-lamp-01",
    title: "Schaltsymbol Lampe",
    category: "symbol",
    topic: "electricity",
    src: base + "symbols/lamp.svg",
    alt: "Schaltsymbol einer Lampe als Kreis mit Kreuz",
    credit: "Eigene Vektorgrafik · Physik 3",
    license: "Projektintern erstellt",
    standardNote: "IEC-orientierte europäische Unterrichtsdarstellung; eigenständig gezeichnet.",
    sourceRefs: ["P3-K3-S045-M02"],
    usage: ["matching", "diagram"],
  },
  switchOpenSymbol: {
    id: "el-symbol-switch-open-01",
    title: "Schaltsymbol Schalter offen",
    category: "symbol",
    topic: "electricity",
    src: base + "symbols/switch-open.svg",
    alt: "Schaltsymbol eines geöffneten Schalters",
    credit: "Eigene Vektorgrafik · Physik 3",
    license: "Projektintern erstellt",
    standardNote: "IEC-orientierte europäische Unterrichtsdarstellung; eigenständig gezeichnet.",
    sourceRefs: ["P3-K3-S045-M02"],
    usage: ["matching", "diagram"],
  },
  switchClosedSymbol: {
    id: "el-symbol-switch-closed-01",
    title: "Schaltsymbol Schalter geschlossen",
    category: "symbol",
    topic: "electricity",
    src: base + "symbols/switch-closed.svg",
    alt: "Schaltsymbol eines geschlossenen Schalters",
    credit: "Eigene Vektorgrafik · Physik 3",
    license: "Projektintern erstellt",
    standardNote: "IEC-orientierte europäische Unterrichtsdarstellung; eigenständig gezeichnet.",
    sourceRefs: ["P3-K3-S045-M02"],
    usage: ["matching", "diagram"],
  },
  resistorSymbol: {
    id: "el-symbol-resistor-01",
    title: "Schaltsymbol Widerstand",
    category: "symbol",
    topic: "electricity",
    src: base + "symbols/resistor.svg",
    alt: "Europäisches Schaltsymbol eines Widerstands als Rechteck",
    credit: "Eigene Vektorgrafik · Physik 3",
    license: "Projektintern erstellt",
    standardNote: "IEC-orientierte europäische Unterrichtsdarstellung; eigenständig gezeichnet.",
    sourceRefs: ["P3-K3-S048-M01", "P3-K3-S048-M02"],
    usage: ["matching", "diagram"],
  },
  ammeterSymbol: {
    id: "el-symbol-ammeter-01",
    title: "Schaltsymbol Amperemeter",
    category: "symbol",
    topic: "electricity",
    src: base + "symbols/ammeter.svg",
    alt: "Schaltsymbol eines Amperemeters als Kreis mit A",
    credit: "Eigene Vektorgrafik · Physik 3",
    license: "Projektintern erstellt",
    standardNote: "IEC-orientierte europäische Unterrichtsdarstellung; eigenständig gezeichnet.",
    sourceRefs: ["P3-K3-S047-M01", "P3-FD-018"],
    usage: ["matching", "diagram"],
  },
  circuitDiagram: {
    id: "el-diagram-basic-circuit-01",
    title: "Stromkreis mit Lampe, Amperemeter, Spannungsquelle und offenem Schalter",
    category: "diagram",
    topic: "electricity",
    src: base + "diagrams/basic-circuit.svg",
    alt: "Schaltbild eines Stromkreises mit Batterie links, Lampe oben, Amperemeter rechts und offenem Schalter unten",
    credit: "Eigene Vektorgrafik · Physik 3",
    license: "Projektintern erstellt",
    sourceRefs: ["P3-K3-S044-M02", "P3-K3-S045-M02", "P3-K3-S047-M01"],
    usage: ["diagram-labeling", "hotspot"],
  },
};

export function asMediaImage(asset: PhysicsAsset) {
  return {
    id: asset.id,
    kind: "image" as const,
    src: asset.src,
    alt: asset.alt,
    caption: asset.title,
    credit: asset.credit,
  };
}
